name: Release
on:
  push:
    branches:
      - master
env:
  PROTOBUF_SHA: 655310ca192a6e3a050e0ca0b7084a2968072260
jobs:
  protoc-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            artifact: protoc-macos
            bazel_installer_sha: b4c94148f52854b89cff5de38a9eeeb4b0bcb3fb3a027330c46c468d9ea0898b
          - os: ubuntu-latest
            graal_url: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz
            artifact: protoc-linux
            bazel_installer_sha: d6cea18d59e9c90c7ec417b2645834f968132de16d0022c7439b1e60438eb8c9
    env:
      BAZEL_INSTALLER_SHA: ${{ matrix.bazel_installer_sha }}
      BAZEL_BIN_LOC: "${{ github.workspace }}/.bazel-cache/bazel-bin"
      BAZEL_VERSION: 2.1.1
    steps:
      - uses: actions/checkout@v2
      - name: Bazel output cache
        id: cache-bazel
        uses: actions/cache@v1
        with:
          path: "${{ github.workspace }}/.bazel-cache"
          key: ${{ runner.os }}-bazel-out-${{ github.run_id}}
          restore-keys: |
            ${{ runner.os }}-bazel-out-
      - name: Configure bazel config for actions
        run: |
          echo "build --config github_actions" > user.bazelrc
          echo "build --disk_cache ${{ github.workspace }}/.bazel-cache/disk-cache" >> user.bazelrc
          echo "build --repository_cache ${{ github.workspace }}/.bazel-cache/repo-cache" >> user.bazelrc
      - name: Install bazel
        run: ./ci_scripts/ci_install_bazel.sh
      - name: Build protoc
        run: ./ci_scripts/build_protoc.sh
      - name: Prepare outputs from platform run
        run: ./ci_scripts/prepare_output.sh ${{ matrix.artifact }} staging-directory
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.artifact }}
          path: staging-directory
  make_release:
    name: Make release
    needs: protoc-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download linux protoc
        uses: actions/download-artifact@v1
        with:
          name: protoc-linux
          path: downloads
      - name: Download macos protoc
        uses: actions/download-artifact@v1
        with:
          name: protoc-macos
          path: downloads
      - name: show downloads
        run : ls -R downloads
      - name: Build update_dependencies.sh
        run: ./ci_scripts/make_update_dependencies.sh "v0.1-${{ github.run_number }}"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.1-${{ github.run_number }}"
          prerelease: false
          title: "Auto generated release"
          files: |
            downloads/protoc-macos
            downloads/protoc-macos.sha256
            downloads/protoc-linux
            downloads/protoc-linux.sha256
            update_dependencies.sh
        id: "automatic_releases"
